"""add_precision_fields_to_industrial

Revision ID: 06119ef54a79
Revises: 4fee7b106d9c
Create Date: 2026-01-21 22:51:11.139066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06119ef54a79'
down_revision = '4fee7b106d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('industrial_assets', sa.Column('load_factor', sa.Float(), nullable=True))
    op.add_column('industrial_assets', sa.Column('power_factor', sa.Float(), nullable=True))
    op.add_column('industrial_assets', sa.Column('op_days_per_month', sa.Integer(), nullable=True))
    op.add_column('industrial_settings', sa.Column('energy_cost_per_kwh', sa.Float(), nullable=True))
    op.add_column('industrial_settings', sa.Column('currency_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('industrial_settings', 'currency_code')
    op.drop_column('industrial_settings', 'energy_cost_per_kwh')
    op.drop_column('industrial_assets', 'op_days_per_month')
    op.drop_column('industrial_assets', 'power_factor')
    op.drop_column('industrial_assets', 'load_factor')
    # ### end Alembic commands ###
