"""Add residential models

Revision ID: 17f6bb1e474e
Revises: 06119ef54a79
Create Date: 2026-01-22 12:23:57.665511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f6bb1e474e'
down_revision = '06119ef54a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumption_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reading_value', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reading_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumption_readings_id'), 'consumption_readings', ['id'], unique=False)
    op.create_index(op.f('ix_consumption_readings_user_id'), 'consumption_readings', ['user_id'], unique=False)
    op.create_table('residential_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_high_impact', sa.Boolean(), nullable=True),
    sa.Column('expert_check_value', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('monthly_cost_estimate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_residential_assets_id'), 'residential_assets', ['id'], unique=False)
    op.create_index(op.f('ix_residential_assets_user_id'), 'residential_assets', ['user_id'], unique=False)
    op.create_table('residential_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('house_type', sa.String(length=50), nullable=True),
    sa.Column('occupants', sa.Integer(), nullable=True),
    sa.Column('area_sqm', sa.Float(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('stratum', sa.Integer(), nullable=True),
    sa.Column('occupancy_profile', sa.String(length=50), nullable=True),
    sa.Column('energy_source', sa.String(length=50), nullable=True),
    sa.Column('monthly_bill_avg', sa.Float(), nullable=True),
    sa.Column('target_monthly_bill', sa.Float(), nullable=True),
    sa.Column('average_kwh_captured', sa.Float(), nullable=True),
    sa.Column('history_kwh', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_residential_profiles_id'), 'residential_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_residential_profiles_user_id'), 'residential_profiles', ['user_id'], unique=True)
    op.create_table('roi_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('target_efficiency', sa.Float(), nullable=False),
    sa.Column('investment_usd', sa.Float(), nullable=False),
    sa.Column('annual_savings_usd', sa.Float(), nullable=False),
    sa.Column('payback_months', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['industrial_assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roi_scenarios_id'), 'roi_scenarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roi_scenarios', type_='foreignkey')
    op.drop_constraint(None, 'roi_scenarios', type_='foreignkey')
    op.create_foreign_key(op.f('roi_scenarios_asset_id_fkey'), 'roi_scenarios', 'industrial_assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('roi_scenarios_user_id_fkey'), 'roi_scenarios', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_roi_scenarios_id'), table_name='roi_scenarios')
    op.alter_column('roi_scenarios', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('roi_scenarios', 'asset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_residential_profiles_user_id'), table_name='residential_profiles')
    op.drop_index(op.f('ix_residential_profiles_id'), table_name='residential_profiles')
    op.drop_table('residential_profiles')
    op.drop_index(op.f('ix_residential_assets_user_id'), table_name='residential_assets')
    op.drop_index(op.f('ix_residential_assets_id'), table_name='residential_assets')
    op.drop_table('residential_assets')
    op.drop_index(op.f('ix_consumption_readings_user_id'), table_name='consumption_readings')
    op.drop_index(op.f('ix_consumption_readings_id'), table_name='consumption_readings')
    op.drop_table('consumption_readings')
    # ### end Alembic commands ###
