"""Add industrial settings table

Revision ID: 4fee7b106d9c
Revises: 6e5d7082739d
Create Date: 2026-01-21 21:33:20.734954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fee7b106d9c'
down_revision = '6e5d7082739d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industrial_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('industry_sector', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('monthly_budget_limit', sa.Float(), nullable=True),
    sa.Column('auto_optimize', sa.Boolean(), nullable=True),
    sa.Column('email_alerts', sa.Boolean(), nullable=True),
    sa.Column('sms_alerts', sa.Boolean(), nullable=True),
    sa.Column('push_notifications', sa.Boolean(), nullable=True),
    sa.Column('critical_alerts', sa.Boolean(), nullable=True),
    sa.Column('dark_mode', sa.Boolean(), nullable=True),
    sa.Column('show_co2', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_industrial_settings_id'), 'industrial_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_industrial_settings_id'), table_name='industrial_settings')
    op.drop_table('industrial_settings')
    # ### end Alembic commands ###
