"""add_gamification_tables

Revision ID: 985051fe5578
Revises: 17f6bb1e474e
Create Date: 2026-01-23 17:40:09.109087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985051fe5578'
down_revision = '17f6bb1e474e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consumption_readings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_consumption_user_date', 'consumption_readings', ['user_id', 'date'], unique=False)
    op.drop_constraint(None, 'consumption_readings', type_='foreignkey')
    op.create_foreign_key(None, 'consumption_readings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('industrial_assets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_industrial_assets_user_id'), 'industrial_assets', ['user_id'], unique=False)
    op.create_index('ix_industrial_assets_user_id_location', 'industrial_assets', ['user_id', 'location'], unique=False)
    op.drop_constraint(None, 'industrial_assets', type_='foreignkey')
    op.create_foreign_key(None, 'industrial_assets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('industrial_settings', sa.Column('ai_autonomy_level', sa.Integer(), nullable=True))
    op.add_column('industrial_settings', sa.Column('peak_shaving_enabled', sa.Boolean(), nullable=True))
    op.add_column('residential_assets', sa.Column('power_watts', sa.Float(), nullable=True))
    op.add_column('residential_assets', sa.Column('daily_hours', sa.Float(), nullable=True))
    op.alter_column('residential_assets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'residential_assets', type_='foreignkey')
    op.create_foreign_key(None, 'residential_assets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('residential_assets', 'expert_check_value')
    op.alter_column('residential_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'residential_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'residential_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'residential_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'residential_profiles', 'users', ['user_id'], ['id'])
    op.alter_column('residential_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('residential_assets', sa.Column('expert_check_value', sa.BOOLEAN(), nullable=True))
    op.drop_constraint(None, 'residential_assets', type_='foreignkey')
    op.create_foreign_key(None, 'residential_assets', 'users', ['user_id'], ['id'])
    op.alter_column('residential_assets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('residential_assets', 'daily_hours')
    op.drop_column('residential_assets', 'power_watts')
    op.drop_column('industrial_settings', 'peak_shaving_enabled')
    op.drop_column('industrial_settings', 'ai_autonomy_level')
    op.drop_constraint(None, 'industrial_assets', type_='foreignkey')
    op.create_foreign_key(None, 'industrial_assets', 'users', ['user_id'], ['id'])
    op.drop_index('ix_industrial_assets_user_id_location', table_name='industrial_assets')
    op.drop_index(op.f('ix_industrial_assets_user_id'), table_name='industrial_assets')
    op.alter_column('industrial_assets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'consumption_readings', type_='foreignkey')
    op.create_foreign_key(None, 'consumption_readings', 'users', ['user_id'], ['id'])
    op.drop_index('ix_consumption_user_date', table_name='consumption_readings')
    op.alter_column('consumption_readings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
